version: '3.8'

services:
  # PostgreSQL database for booking-api
  booking-db:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
    ports:
      - "5432:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

  # Booking API (Spring Boot)
  booking-api:
    build:
      context: ./booking-api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/booking_db
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: booking_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - booking-db

  # MySQL database for payment-api
  payment-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: payment_user
      MYSQL_PASSWORD: payment_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - payment_db_data:/var/lib/mysql

  # Payment API (Laravel)
  payment-api:
    build:
      context: ./payment-api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: payment-db
      DB_PORT: 3306
      DB_DATABASE: payment_db
      DB_USERNAME: payment_user
      DB_PASSWORD: payment_password
      APP_KEY: base64:your-app-key-here
    depends_on:
      - payment-db

  # User API (NestJS)
  user-api:
    build:
      context: ./user-api
      dockerfile: docker/dev/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

volumes:
  booking_db_data:
  payment_db_data: